from .errors import PayloadSchemaVersionError
from .options import (
    ConditionalFillProbabilityPlotSettings,
    DashboardSimulationHeatmapSettings,
    FillProbabilityPlotSettings,
    HeatmapAxisSettings,
    ManualColorRange,
    OptionalColorRange,
    OptionalSymmetricColorRange,
    PlotRenderOptions,
    ProfitPlotSettings,
    SimulationHeatmapSettings,
)
from .protocols import PlotBuilder, PlotDatasetLocator
from .types import (
    OrderbookPayloadV1,
    SchemaVersionV1,
    SimulationArraysV1,
    TradesPayloadV1,
    normalize_orderbook_payload_to_v1,
    normalize_simulation_arrays_to_v1,
    normalize_trades_payload_to_v1,
)
from .views import (
    build_fill_probability_view,
    build_micro_cost_fill_probability_view,
    build_micro_profit_view,
    build_mid_cost_fill_probability_view,
    build_mid_profit_view,
    build_orderbook_view,
    build_trade_volume_timeline_view,
    build_trades_scatter_view,
)

__all__ = [
    "ConditionalFillProbabilityPlotSettings",
    "DashboardSimulationHeatmapSettings",
    "FillProbabilityPlotSettings",
    "HeatmapAxisSettings",
    "ManualColorRange",
    "OrderbookPayloadV1",
    "OptionalColorRange",
    "OptionalSymmetricColorRange",
    "PayloadSchemaVersionError",
    "PlotBuilder",
    "PlotDatasetLocator",
    "PlotRenderOptions",
    "ProfitPlotSettings",
    "SchemaVersionV1",
    "SimulationArraysV1",
    "SimulationHeatmapSettings",
    "TradesPayloadV1",
    "build_fill_probability_view",
    "build_micro_cost_fill_probability_view",
    "build_micro_profit_view",
    "build_mid_cost_fill_probability_view",
    "build_mid_profit_view",
    "build_orderbook_view",
    "build_trade_volume_timeline_view",
    "build_trades_scatter_view",
    "normalize_orderbook_payload_to_v1",
    "normalize_simulation_arrays_to_v1",
    "normalize_trades_payload_to_v1",
]
